name: CI

on:
  workflow_dispatch:
  pull_request:
    branches-ignore:
      - 'bump/**'
  push:
    branches:
      ['master']
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Build with Gradle
        run: ./gradlew assembleDebug testDebugUnitTest